args: !!python/object:args.MyArgs
  ArnoldiInit: Chebyshev
  Arnoldippnp: GArnoldi_prop
  FuncName: doesn't matter
  Gamma: null
  Init: Chebyshev
  K: 10
  Vandermonde: false
  alpha: 0.1
  dprate: 0.5
  dropout: 0.5
  e: Chebyshev
  hidden: 128
  hidden_dim: 128
  homophily: false
  lower: 0.0001
  nameFunc: doesn't matter
  upper: 2
ds_info: !!python/object:__main__.DatasetInfo
  N: 2223
  class_weights: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCgAAADUzMjQ1NDE0NTZxAlgDAAAAY3B1cQNLBU50cQRRLoACXXEAWAoAAAA1MzI0NTQx
      NDU2cQFhLgUAAAAAAAAA6m7NPeh9Fj75mUM+felxPpWjpj4=
  - 0
  - !!python/tuple
    - 5
  - !!python/tuple
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  name: squirrel
  num_classes: 5
  num_features: 2089
learning_rate: 5.0e-06
model: !!python/name:models.maxcut.MaxCutClusters ''
