args: !!python/object:args.MyArgs
  ArnoldiInit: Chebyshev
  Arnoldippnp: GArnoldi_prop
  FuncName: doesn't matter
  Gamma: null
  Init: Chebyshev
  K: 10
  Vandermonde: false
  alpha: 0.1
  dprate: 0.5
  dropout: 0.5
  e: Chebyshev
  hidden: 128
  hidden_dim: 128
  homophily: false
  lower: 0.0001
  nameFunc: doesn't matter
  upper: 2
ds_info: !!python/object:__main__.DatasetInfo
  N: 22662
  class_weights: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCgAAADUyNjMyMDkzNDRxAlgDAAAAY3B1cQNLEk50cQRRLoACXXEAWAoAAAA1MjYzMjA5
      MzQ0cQFhLhIAAAAAAAAA7iknPYiPRzy5eEk8SUh8PNDNfTzCO+g8tLP9PBAdEj3eNjk92ABIPVoW
      XD1qTrE9Tlm4Pf8q2D1V0u896lb3PYjj/D1o2Y88
  - 0
  - !!python/tuple
    - 18
  - !!python/tuple
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  name: Roman-empire
  num_classes: 18
  num_features: 300
learning_rate: 5.0e-06
model: !!python/name:models.maxcut.MaxCutClusters ''
